# Generated by Django 5.0.3 on 2024-04-02 00:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_owner',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
