# Generated by Django 5.0.3 on 2024-04-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncs', '0002_chatroom_room_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroom_id', models.CharField(max_length=255)),
                ('sender_id', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
